import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { TopNav } from "~/app/_components/topnav";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";

import { ourFileRouter } from "~/app/api/uploadthing/core";
import { Toaster } from "sonner";
// import { ThemeProvider } from "~/components/theme-provider";

export const metadata: Metadata = {
	title: "T3 Gallery",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
	modal,
}: {
	children: React.ReactNode;
	modal: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang="en" className={`${GeistSans.variable} dark`}>
				<NextSSRPlugin
					routerConfig={extractRouterConfig(ourFileRouter)}
				/>
				<body className="dark">
					{/* <ThemeProvider
						attribute="class"
						defaultTheme="dark"
						forcedTheme="dark"
						disableTransitionOnChange
					> */}
					<div className="h-screen grid grid-rows-[auto,1fr]">
						<TopNav />
						<main className="overflow-y-auto">{children}</main>
					</div>
					{modal}
					<div id="modal-root" />
					<Toaster />
					{/* </ThemeProvider> */}
				</body>
			</html>
		</ClerkProvider>
	);
}
